services:
  - type: web
    name: my-portfolio
    runtime: python
    pythonVersion: 3.9
    buildCommand: pip install -r requirements.txt
    startCommand: flet publish web && flet run --web --port $PORT
    envVars:
      - key: FLET_WEB_RENDERER
        value: "auto"
    autoDeploy: true
    healthCheckPath: /
